#!/bin/bash
#SBATCH --job-name=4_4_job
#SBATCH --time=00:10:00
#SBATCH --mem=16G
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --output=4x4_a2.%j.out
#SBATCH --ntasks-per-node=2
#SBATCH --partition=defq


module load openmpi-4.1.4-gcc-11.2.0-6z47sq3

if [ ! -f asgn2 ]
then
 mpicc asgn2.c -o asgn2 -lm
else
 if [ asgn2.c -nt asgn2 ]
then
 mpicc asgn2.c -o asgn2
 fi
fi

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun asgnv2 4 4 60
